apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  namespace: default
  labels:
    app: helloworld
  annotations:
    imageregistry: "http://127.0.0.1:5000/"
spec:
  containers:
  - name: helloworld
    image: demo
    ports:
      - containerPort: 8080