apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: default
  labels:
    app: helloworld
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30090
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: registry.cn-shanghai.aliyuncs.com/cody_test_demo/hello:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      imagePullSecrets:
        - name: yun
      containers:
        - name: helloworld
          image: registry.cn-shanghai.aliyuncs.com/cody_test_demo/hello:1.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080


