apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld
  namespace: default
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: 127.0.0.1:5000/demo
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080